### ISSUE TITLE
Images do not re-size when Carousel width and height are increased 

### ISSUE THREAD

**Issue by bgraham1125** [BlackrockDigital/startbootstrap-heroic-features#2]
Increasing the width and height of the carousel does work, however,  although it moves position on the page, it does not permit the images to display in larger sizes.  This regardless of whether resize Image is set to true or false. How do I also increase the image sizes? I am unable to send a link because it is running locally.

Thank you.

Bill Graham

**Comment by davidtmiller** [comment]
There isn't a carousel included with this template. Make sure you're using larger images in a carousel though and you can always use the .img-responsive class to make them resize responsively.
