### ISSUE TITLE
Adding forms/form values to template

### ISSUE THREAD

**Issue by TJack06** [BlackrockDigital/startbootstrap-heroic-features#5]
I'm trying to add a form to you template.  However, when I do, it doesn't return all the inputs from the form.  My boss loves your template; however, can't seem to get it to pass the form data fields.  I'm sure the update needs to be made in the jquery file using the serialize() method, but I'm unfamiliar with JQuery/AJax and can't seem to find where this code needs to be updated.  Can you help me, please?

**Comment by jona950** [comment]
so easy! Thanks
